spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YifengGuo/FlinkTest
          username: gyf940517@gmail.com
          password: FFloveXX517218
server:
  port: 1201